base_path: "compose-multiplatform"
preserve_hierarchy: false

files:
  - source: "/**/composeResources/values/strings.xml"
    translation: "/%original_path%-%android_code%/%original_file_name%"
  - source: "/**/res/values/strings.xml"
    translation: "/%original_path%-%android_code%/%original_file_name%"
